GET http://localhost:5000


###Login route
POST  http://localhost:5000/auth/login

Content-Type: : application/json

{
  "email":"kalpeshw@gmail.com",
  "password":"123"
}

###Register route
POST  http://localhost:5000/auth/register

Content-Type: : application/json

{
   "email":"kalpesh@gmail.com",
    "password":"123"
}

###refresh-token route
POST  http://localhost:5000/auth/refresh-token


###LogOut route
DELETE  http://localhost:5000/auth/logout

